### ISSUE TITLE
Custom waypoint icons 

### ISSUE THREAD

**Issue by barbieswimcrew** [Raruto/leaflet-elevation#100]
I'm very sorry to start this issue but I'm currently trying for hours to get custom waypoint icons work like described in the leaflet-gpx docs (https://github.com/mpetazzoni/leaflet-gpx#about-waypoints). I already have <sym> in the gpx waypoints but it seems no matter what I do the red pins will be used any time. 

I even tried your example (https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_gpx-waypoints.html) but can't get it work... do you have any idea how to get different icons for different <sym> waypoints?

Sorry for the inconvenience and thanks a lot for your help!

**Comment by Raruto** [comment]
Hi Martin,
since version 1.6 i've replaced the [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx) library with [tmcw/togeojson](https://github.com/tmcw/togeojson) (see: https://github.com/Raruto/leaflet-elevation/issues/97#issuecomment-792132351)

As you can see, not all examples have been updated to this latest version yet, anyway, you can take a look at the following lines:

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/options.js#L28-L33

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/utils.js#L92

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/utils.js#L100

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/index.css#L248-L254

For example:

- you can listen to that event and selectively set the icon using some core methods (see: [L.Marker::setIcon](https://leafletjs.com/reference-1.7.1.html#marker-seticon))
- you can use a your own geojson data loader (eg. https://github.com/Raruto/leaflet-elevation/issues/3#issuecomment-489056500, see: [GeoJSONLoader](https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/utils.js#L70-L145) for a comprehensive setup)
- or, as usual, propose a resolutive pull request

_Have a nice Day,
Raruto_

**Comment by barbieswimcrew** [comment]
Thank you so much for your response. As far as I can see listening to the waypoint_added event would help to set the marker's icon individually. Thanks for that hint! But there's one thing I don't get right now... I can't access to the waypoints <sym> property somehow... would the only way to access to add the feature to the event data like this?

`control.fire('waypoint_added', {point: marker, point_type: 'waypoint', element: latlng, feature: feature});`

By doing this way I'd be able to access "data.feature.properties.sym" in the event listener... or am I doing anything wrong?

**Comment by Raruto** [comment]
At the moment, since you are going to use [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx) library, you can build a custom function like the following:

https://github.com/Raruto/leaflet-elevation/blob/61a0ef213c81e4ff2a0bdfb938e674d9f52cd113/src/utils.js#L138-L171

As far I know, the [tmcw/togeojson](https://github.com/tmcw/togeojson) library should also support `<sym>` tags but that's a feature I've never used before... 

> I can't access to the waypoints property somehow... would the only way to access to add the feature to the event data like this?
> ```js
> control.fire('waypoint_added', {point: marker, point_type: 'waypoint', element: latlng, feature: feature});
> ```
> By doing this way I'd be able to access "data.feature.properties.sym" in the event listener... or am I doing anything wrong?

If you are able to reproduce a working example with togeojson library, I might consider whether to merge that.

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
From version **1.6.8** you can also use the `<sym>` tag, however, there are many ways to set a custom icon.

Take a look at the updated examples to see a possible one:

- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_geojson-waypoints.html
- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_gpx-waypoints.html
