### ISSUE TITLE
Adding distance to the vertical line that shows up in a GPX path

### ISSUE THREAD

**Issue by leandroprz** [Raruto/leaflet-elevation#110]
Hi,

I was wondering if it is possible to show the distance instead of the elevation in the vertical line that shows up when hovering the cursor over a GPX path? This one: https://i.ibb.co/gd99DVs/elevation-leaflet.png (sorry, I don't know how it's called)

This is my code right now:

```js
      var elevation_options = {
          theme: 'custom-theme',
          detached: false,
          autohide: true,
          collapsed: true,
          position: 'bottomleft',
          distance: true,
          altitude: true,
          summary: 'inline',
          downloadLink: false,
          ruler: false,
          legend: false,
          preferCanvas: false
      };

      var controlElevation = L.control.elevation(elevation_options).addTo(mapita);
      controlElevation.load('tracks/track-123.gpx');
```

**Comment by Raruto** [comment]
Hi Leandro,
you can take a try with the following "private" function: https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/control.js#L759

here is an example of how to use it:
https://github.com/Raruto/leaflet-elevation/blob/97bdf8a66420f66d19097ee301a66a1226cd555b/src/slope.js#L96-L100

and here is a sample implementation of how to write a small library in order to extend the default chart behavior
(NB it may contain partially obsolete code):

- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html
- https://github.com/Raruto/leaflet-elevation/blob/master/libs/extended-ui.js

As usual, proposal pull requests are welcome.

_Happy Friday,
Raruto_
