### ISSUE TITLE
Speed instead of elevation

### ISSUE THREAD

**Issue by oe8bck** [Raruto/leaflet-elevation#121]
Hi,

I like this plugin very much, but I would need it with the speed information (or other info like e.g. heart-rate)

Maybe someone can give me a hint where to start if I would like to add this to this plugin. Or is there another plugin for this?

KR,
Christof

**Comment by Raruto** [comment]
Hi Christof,
heart rate is not implemented, however (with a little js), you can extend library behavior in order to create a custom profile)

To show speed graph profile you can look at this example: 
- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_speed-chart.html

If it can help you, here you will find other useful code:

- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_slope-chart.html
- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html
- https://github.com/Raruto/leaflet-elevation/blob/master/src/speed.js
- https://github.com/Raruto/leaflet-elevation/blob/master/src/slope.js

_Have a nice day,
Raruto_
