### ISSUE TITLE
How to minify?

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#157]
Hi Raruto,

I made a pull request, you accepted it, thank you. But the new leaflet-gpxgroup.js is not minified yet.
For the next time should I do this? If yes, how? Or do you minify it?

Thank you very much.

**Comment by Raruto** [comment]
Hi hupe13,
as stated here: https://github.com/Raruto/leaflet-elevation/pull/59#issuecomment-639643391

> I use the **Google Closure Compiler** through the [atom-minify](https://atom.io/packages/atom-minify) package.

Anyway yes, if you can, send them already minified.

Keep in mind that in later versions the "leaflet-gpx" dependency has been superseded (https://github.com/Raruto/leaflet-elevation/commit/0df53e92b6a8ba73bddd254bd59540d71ca1e47f). Anyone interested should take some time to update that [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html) using the latest togeojson library...

_Happy testing,
Raruto_

**Comment by hupe13** [comment]
Hi Raruto,

I published this in my plugin and someone found the [bug](https://wordpress.org/support/topic/very-interesting-plugin-12/#post-15023486):

>  I observed that the hover system works correctly but clicking on a track polyline makes it disappear. The track control on the uppper left is still functional but you can’t get make the tracks visible without a page  refresh.  

You can see this [here](https://leafext.de/en/doku/elevation/multielevation/).

I investigated and tested the behavior.  If I comment out the line 2159 in leaflet-elevation.js
```
diff leaflet-elevation.js leaflet-elevation-leafext.js
2159c2159
<         if (this._layers) this._clearLayers();
---
>         //if (this._layers) this._clearLayers();
```
it works. But I cannot assess what effects this will have on other functions. 

Thank you.

**Comment by Raruto** [comment]
Since version **1.7.3** it should finally work without the leaflet-gpx library (replaced by togeojson: https://github.com/Raruto/leaflet-elevation/commit/ce9ad7a573fec4cb03ee44208e1e4014f08c32eb)

Here the updated examples:

- [leaflet-elevation_toggable-charts.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_toggable-charts.html)
- [leaflet-elevation_hoverable-tracks.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html)

_Raruto_

**Comment by hupe13** [comment]
Thank you very much, it works now in my test installation.
