### ISSUE TITLE
Speed in min / km (running pace)

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#183]
Hi Raruto,

someone in my forum asks: 
There is no option to show the PACE (in min/km) instead of SPEED (in km/h). For runners, an information 12 km/h is nearly useless, we’ll measure with 6:12 min/km.  Is it possible, to provide an option for this?
Another question is: 
The distance (in elevation chart) is every 2 km. Is it possible to change this? If I can configure this, please give me a hint.

Thank you very much.

**Comment by Raruto** [comment]
Hi hupe,

> There is no option to show the PACE (in min/km) instead of SPEED (in km/h). For runners, an information 12 km/h is nearly useless, we’ll measure with 6:12 min/km. Is it possible, to provide an option for this?

Currently no, but starting from [**version 2.0.0**](https://github.com/Raruto/leaflet-elevation/releases/tag/v2.0.0) I tried to standardize the process that should allow the use of custom extensions (you can check out [`src/handlers`](https://github.com/Raruto/leaflet-elevation/tree/master/src/handlers) and [leaflet-elevation_extended-ui.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html) for an initial approach). In addition to this, I warn you that from this version only the really necessary components are loaded as needed (if the classes are not found in the global scope), if you don't like it you can always create a your own static bundle that exposes the definitions of the classes that you really intend to use (maybe it's not very clear, but you can check [here](https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/control.js#L235-L245) and [here](https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/control.js#L725-L748) to better understand the actual process of code injection, anyway, you can understand how it works in detail, through the same example above [leaflet-elevation_extended-ui.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html)).

>  The distance (in elevation chart) is every 2 km. Is it possible to change this? If I can configure this, please give me a hint.

The tick size issue is a bit tricky because first you have to understand how d3 works (which is a fairly low level library), however, I would like to point out some of [these](https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/options.js#L75-L76) options that allow you to alter the total number of ticks to show (probably it is it is also possible to set a predefined width, but I'm not so much versed in this library). For more information you can also start from here:

- https://github.com/d3/d3-axis
- https://github.com/Raruto/leaflet-elevation/issues/170
- https://github.com/Raruto/leaflet-elevation/blob/master/src/components/d3.js#L40-L94

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
Thanks very much. I'll take a look at it.

**Comment by Raruto** [comment]
In version **2.2.0** i added some sample code within the [leaflet-elevation_extended-ui.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html) demo.

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/examples/leaflet-elevation_extended-ui.html#L262

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/examples/leaflet-elevation_extended-ui.html#L270

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/examples/leaflet-elevation_extended-ui.html#L156-L219

---

However, that function is also present among the built-in handlers (the example is purely demonstrative on how to use your own custom handler), as usual, improved edits and pull requests are always welcome:

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/src/handlers/pace.js#L1-L65

_Have a nice day,
Raruto_
