### ISSUE TITLE
Undefined "map" variable after updating to 2.1.0

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#184]
Hi Raruto,

testing version 2.1.0 I get an error:
> Uncaught (in promise) ReferenceError: map is not defined

When I change in leaflet-elevation.js the lines 910, 917 and 918  from "map" to "this._map"  the error is gone and I get a map with an elevation chart. It looks different than before, but it works.

But more errors must exist. Many of the users (including me) have multiple maps on one page, this does not work. Or the acceleration of my test data is "Infinity" (with version 1.7.6 it is correct). The developer console does not show any errors. And I don't know what could be wrong.

Thank you very much.

**Comment by Raruto** [comment]
Hi hupe,

> When I change in leaflet-elevation.js the lines 910, 917 and 918 from "map" to "this._map" the error is gone and I get a map with an elevation chart. It looks different than before, but it works.

please make use of [line permalinks](https://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github/45578779#45578779) to `src` files when describing an issue (this way anyone reading it now and in the future can understand exactly what you are referring to).

> But more errors must exist. Many of the users (including me) have multiple maps on one page, this does not work.

Yep, version 2.x has undergone [a lot of code refactoring](https://github.com/Raruto/leaflet-elevation/releases/tag/v2.0.0) (and unfortunately I don't have much time to devote to testing). In order to solve this problem faster I suggest you propose yourself a pull that adds an example that loads two maps (that way at least we have some material to work on).

> Or the acceleration of my test data is "Infinity" (with version 1.7.6 it is correct).

If I'm not mistaken you are referring to the values calculated by the following functions (if you get infinity I assume that a numerical value is never calculated), essentially these functions iteratively update the max / min value every time a new point is added to the chart (during initial data loading):

https://github.com/Raruto/leaflet-elevation/blob/0a2523d786ec9495262754a5c4956d66a7caa595/src/utils.js#L134-L135

To help you in debugging, I point out below the points in the code where they are called:

https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/handlers/acceleration.js#L22

https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/control.js#L1034-L1039

This last portion creates and assigns the value `track_info.acceleration_max` and `track_info.acceleration_min` (it may seem convoluted but on this point I have tried to maintain a minimum of compatibility with the nomenclature of the previous versions).

> The developer console does not show any errors. And I don't know what could be wrong.

When in doubt, see what your computed data contains (eg. `console.log(controlElevation._data);`):

- https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/control.js#L180
- https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/control.js#L170

**Comment by Raruto** [comment]
**PS** anyway take a look at this whole function too because I guess the bug could be hiding in there

https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/control.js#L1000-L1058

**Comment by Raruto** [comment]
Or it's just a matter of wrong logic:

```js
(iVal, max) => (iVal > max ? iVal : max) || -Infinity;  
```

For example: `0 || Infinity` --> `Infinity`

**Comment by hupe13** [comment]
When the setting for `time` is false, the charts for acceleration and speed do not work, the values are always "0".

I have detected the parameter `hotline`, but only `false `and `"elevation"` work.  With `"elevation"` the track is nice and colorful. It may be that I don't have the right example for it, but with '"slope"' and the others the track  is always red .

**Comment by Raruto** [comment]
> When the setting for time is false, the charts for acceleration and speed do not work, the values are always "0".

> I have detected the parameter hotline, but only false and "elevation" work. With "elevation" the track is nice and colorful. It may be that I don't have the right example for it, but with "slope" and the others the track is always red .

Hi hupe, I don't quite understand what this has to do with the problem described above (please try to open only one issue per problem, otherwise it becomes difficult for everyone to follow the thread)

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
Sorry, you are right, I will open new issues.
When I solved all my problems with version 2.1.0, I will make a pull request, if necessary.

**Comment by Raruto** [comment]
Ok, don't bother asking questions when in doubt 😉

_Raruto_

**Comment by hupe13** [comment]
Of course I will ask ..., I have many questions (see above).
