### ISSUE TITLE
speed and acceleration chart if time is false

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#188]
### Subject of the issue
No charts and values for speed and acceleration if time is false

### Your environment
* leaflet-elevation: 2.1.0

### Steps to reproduce

```js
elevationControl: {
	url: "https://url/to/file.gpx", 
		options: {
			detached: true,
			summary: "inline",
			imperial: false,
			slope: false,
			speed: true,
			acceleration: true,
			time: false,
			hotline: false,
                       ....
		},
	},

```

### Expected behaviour
charts for speed and acceleration should appear

### Actual behaviour
do not appear, values are 0

https://github.com/Raruto/leaflet-elevation/blob/9aca816eb7c76b5d8db7337513020d9c41e441fa/src/control.js#L235-L243
After these lines insert the code:

```js
if ((modules.includes("Speed") || modules.includes("Acceleration")) && ! modules.includes("Time")) {
	modules.splice(1, 0, "Time");
}
```
Then it works.
I do not a pull request yet, I have more issues.

**Comment by Raruto** [comment]
Hi hupe,

as you notice this line may have an incorrect condition:

https://github.com/Raruto/leaflet-elevation/blob/9aca816eb7c76b5d8db7337513020d9c41e441fa/src/control.js#L243

if necessary, you can also check the following:

https://github.com/Raruto/leaflet-elevation/blob/9aca816eb7c76b5d8db7337513020d9c41e441fa/src/handlers/time.js#L35

https://github.com/Raruto/leaflet-elevation/blob/9aca816eb7c76b5d8db7337513020d9c41e441fa/src/control.js#L1095

**Comment by hupe13** [comment]
I put a console.log around these lines. According to console.log it is too late. It is logical: if I want to calculate speed and acceleration, I need the time. Since time is false, the module is not loaded.

**Comment by Raruto** [comment]
> It is logical: if I want to calculate speed and acceleration, I need the time. Since time is false, the module is not loaded.

So your advice is to use: `time: true` or `time: "disabled"` as default?

https://github.com/Raruto/leaflet-elevation/blob/9aca816eb7c76b5d8db7337513020d9c41e441fa/src/options.js#L49

**Comment by hupe13** [comment]
No. It is a WordPress Plugin. I want to provide all possible options. It is possible that a user wants just this combination.
`time: false, speed: true` and / or `time: false, acceleration: true`.
Like [here](https://leafext.de/en/elevation/liste/?testing=speed) and [here](https://leafext.de/en/elevation/liste/?testing=acceleration). But there is leaflet-elevation version 1.7.6 running.

**Comment by Raruto** [comment]
> No. It is a WordPress Plugin. I want to provide all possible options. It is possible that a user wants just this combination.
time: false, speed: true and / or time: false, acceleration: true.

I didn't say to remove options, but to use a different default value for the `time` option, for example

- `time: false, speed: true` --> `time: "disabled", speed: true`
- `time: false, acceleration: true` --> `time: "disabled", acceleration: true`

From what I understand in version 2.x there is no conceptual error, but simply a more rigorous interpretation of the `false` value.

Anyway, I am open to any other kind of solutions.

**Comment by hupe13** [comment]
> It is logical: if I want to calculate speed and acceleration, I need the time. Since time is false, the module is not loaded.

I should say: Even if time is false, the module time.js must be loaded, if speed or acceleration are true.

**Comment by hupe13** [comment]
You wrote in README.md and I realized with leaflet-elevation version 1.7.6 this:

>     // Display time info: true || "summary" || false

https://leafext.de/en/elevation/liste/?testing=time

>     // Display distance info: true || "summary"

https://leafext.de/en/elevation/liste/?testing=distance

**Comment by Raruto** [comment]
> You wrote in README.md
>
> ```js
> // Display time info: true || "summary" || false
> ```

Code never lies, comments sometimes do 😄

> I realized with leaflet-elevation version 1.7.6 this:

yes, I understood that from version 1.7.6 something can be changed, after all we are dealing with a version major update (2.x) and, just to avoid potential confusion, my intention was to standardize the use of these keywords across all profiles (then that this is true I do not know, I have not had time to test my statements).

```js
// true || "summary" || "disabled" || false
```

---

> Even if time is false, the module time.js must be loaded, if speed or acceleration are true.

I will be happy to merge any of your proposals if you can find a generic way to handle this (that is, it doesn't just apply to the `time` option, but also to any other base type).

My initial idea was to do something as follows (to define some sort of dependency relation):

https://github.com/Raruto/leaflet-elevation/blob/c76e10bb1d30b9e53af6a238cb8973dd256b7d93/src/handlers/time.js#L35

But obviously the following line seems to contradict this idea (as it excludes `false` values), and here I return to my earlier statement: are we really sure we have a bug here? (all other handlers are also not loaded when they are false, isn't that the sense of that value?)

https://github.com/Raruto/leaflet-elevation/blob/c76e10bb1d30b9e53af6a238cb8973dd256b7d93/src/control.js#L243

that's why I was wondering what the differences were: `time: false <--> time: "disabled"` (regardless of what has been documented)

_Have a nice Saturday,
Raruto_

**Comment by hupe13** [comment]
I think I know what you want now. Let's see ...

**Comment by Raruto** [comment]
Version **2.2.0** should better handle this issue.

---

I also updated the readme file (basically the `"disabled"` value is available / makes sense for all those options that also show a profile), like so:

```js
// Acceleration chart profile: true || "summary" || "disabled" || false
acceleration: false,

// Slope chart profile: true || "summary" || "disabled" || false
slope: false,

// Speed chart profile: true || "summary" || "disabled" || false
speed: false,

// Altitude chart profile: true || "summary" || "disabled" || false
altitude: true,
```

```js
// Display time info: true || "summary" || false
time: true,

// Display distance info: true || "summary" || false
distance: true,
```

---

Basically, since I realized that this problem could also arise in other cases (eg. `acceleration: true` + `speed: false`, `slope: true` + `altitude: false`, ...), in this version I just removed the following check:

https://github.com/Raruto/leaflet-elevation/blob/c76e10bb1d30b9e53af6a238cb8973dd256b7d93/src/control.js#L243

in favor of the `handlers` option:

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/src/options.js#L20

I'm still not sure if this is the final solution, but at least for now you can just redefine this array to choose which files you want to include (the so-called dynamic import feature). Below a practical example of operation in conjunction with custom handlers:

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/examples/leaflet-elevation_extended-ui.html#L255-L271

---

_Have a nice testing,
Raruto_

**Comment by hupe13** [comment]
This works now, thank you very much!
