### ISSUE TITLE
GPX not loaded (sometimes !)

### ISSUE THREAD

**Issue by chaosad2802** [Raruto/leaflet-elevation#191]
### Your environment
* leaflet-elevation: __2.1.0 / 1.9.4__
* leaflet: __1.7.1__
* browser: __Firefox - Chrome - Edge__
* operating system: __windows 10 / 11__ 
* link to your project: __https://mymaps.fr (-> v 1.9.4) & https://mymaps.fr/index00.html (-> v 2.1.0)__ 

Hi, thanks for this great code, really useful.
I met a problem with new version (2.1.0)

With version 1.9.4, GPX track is always loaded (red track, with kilometers shown).
With verson 2.1.0, sometimes, map is loaded (with elevation colors, kilometers, and arrows). Sometimes, track is not loaded at all.
I tried to delete cache, to reload map, but it seems to be a random issue.

I'm not an expert with leaflet code ! ;-)

Help !

**Comment by Raruto** [comment]
Hi chaosad282,

version 2.x is a major release still in the adjustement phase, so it may have some problems, starting from this version ([70e230f](https://github.com/Raruto/leaflet-elevation/commit/70e230fedf3d4786262e8db18c12c055d45f6997#diff-53aa5b852a2ae4fc1256622d467574e40ceea689796466f62dfa9cd6c0d66e34)) all non-mandatory components are now excluded from the statically generated bundle and instead dynamically loaded (when required). Probably this issue is related to javascript promises, of which this version makes much more extensive use, in essence it is as if a "callback" function were never invoked.

That said, if you want to try to find the solution, just debug your code from here:

https://github.com/Raruto/leaflet-elevation/blob/c76e10bb1d30b9e53af6a238cb8973dd256b7d93/src/control.js#L217-L222

Otherwise, as suggested here https://github.com/Raruto/leaflet-elevation/issues/182#issuecomment-1076620843, you can alternatively try to manually include all dependencies required by this library.

> Sometimes, track is not loaded at all. I tried to delete cache, to reload map, but it seems to be a random issue.

If I'm not mistaken this type of error happens more often at the first loading of a page (at subsequent loads it should disappear immediately).

_Have a nice day,
Raruto_

**Comment by chaosad2802** [comment]
Hi,
Thanks for your answer.
I 'm not good enough too understand what I should try to do... :-(
I gonna wait for updates !

After testing, effectively, this error seems to happen often at the first loading of a page.

Just one more question, when I'm using v 1.9.6 (and more), arrows on track always show right ("east"), and not track direction. Did I miss something ?

**Comment by Raruto** [comment]
> I 'm not good enough too understand what I should try to do... :-(
> I gonna wait for updates !

I understand, but keep in mind that the best way to see a problem solved is to work with it personally (the more people are involved in it, the easier it is to find a solution), I am already trying to do what I can in my spare time...

> Just one more question, when I'm using v 1.9.6 (and more), arrows on track always show right ("east"), and not track direction. Did I miss something ?

I don't know, please if you think it's a bug create a new issue with a reproducible example (I didn't understand if this is the case, but you can understand that I cannot offer support or patches for previous versions of this library).

_Have a nice day,
Raruto_

**Comment by chaosad2802** [comment]
Sure.
Thanks again for your answers, and for your time.
Let me more time, and I'll try to help you when I'll be able to understand
how it works! 😅
I'm a newbie. I just started to code this page few days ago, my really
first html code.
Not so easy to learn all these languages, just watching tutorials and
reading a lot of web pages!
Maybe one day... 🙄
Great job again,
Regards,

**Comment by somini** [comment]
Got hit by this when migrating to v2. Is there a way to publish a bundle yourself, so that we can have a big JS blob that includes all the modules?

By "yourself", I mean unpkg or something.

**Comment by somini** [comment]
https://unpkg.com/browse/@raruto/leaflet-elevation@2.2.6/dist/

For example, this is the "dist" folder, with the "compiled" bundle. There could be another bundle with all the other handlers compiled in.

**Comment by Raruto** [comment]
Hi somini,

> Is there a way to publish a bundle yourself, so that we can have a big JS blob that includes all the modules?

there are several ways to solve your problem (as you can import ES6 modules in a variety of ways), the most suitable one is to create a complete bundle of your entire application (including also the dependencies of your project in order to take advantage of [tree shaking](https://web.dev/reduce-javascript-payloads-with-tree-shaking/) and many other useful features).

> https://unpkg.com/browse/@raruto/leaflet-elevation@2.2.6/dist/
> 
> For example, this is the "dist" folder, with the "compiled" bundle. There could be another bundle with all the other handlers compiled in.

Those files are built in here: [build/rollup.config.js](https://github.com/Raruto/leaflet-elevation/blob/3ee745d71ed172979b7bfe0ff52f7c63214d3c04/build/rollup.config.js), however, you can also include these files https://unpkg.com/browse/@raruto/leaflet-elevation@2.2.6/src/ within your page individually or with the most suitable strategy for your project.

_Have a nice day,
Raruto_

**Comment by somini** [comment]
Thanks for the reply.

The project I'm working on is not JavaScript, I'm just statically generating some HTML with picture thumbnails and a leaflet map for my GPX tracks.
Here's the code: https://gitlab.com/somini/pythumbnailer/

From some preliminary tests, if I load all the components and handlers "by hand", it seems to work. I get 404 errors and just put the downloaded files there.
But everything will need to be located in weird places, relative to the server root, and therefore inaccessible.

- Is it possible to configure `leaflet-elevation.all.js` which concatenates all source files, including components and handlers? This would be published as a separate file from what's already done, no incompatibility would result. Just more deployment options.
- How can I configure the [image folder location](https://unpkg.com/browse/@raruto/leaflet-elevation@2.2.6/images/)? I can download all the SVG files, but again, they are being located in weird places, can I just control its parent location?

**Comment by Raruto** [comment]
Hi somini,

try to take a look at this other repository: https://github.com/Raruto/leaflet-npm/tree/leaflet-rollup to understand and get an idea on how to proceed. For the rest, if someone will make a pull request I will be happy to evaluate it, currently I don't have the time and the interest to code it for you (perhaps try on [stackoverflow.com](https://stackoverflow.com/) for better advices).

_Have a nice day,
Raruto_
