### ISSUE TITLE
hotline

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#193]
### Subject of the issue

hotline option

### Your environment
* leaflet-elevation: 2.2.2

Missing in README:

```html
// hotline: false || "elevation"
```

Or should it more? In your examples is hotline set to `"speed"` and `"slope"` also, but I don't see a coloured track like with `"elevation"`. The track is always red.

**Comment by Raruto** [comment]
As you may know, I didn't develop that library myself (and never used it before), for the moment I have included it here because this line [https://github.com/iosphere/Leaflet.hotline/src/leaflet.hotline.js#L24](https://github.com/iosphere/Leaflet.hotline/blob/49e6f45dc98e1432e6a8f849ba4c2b9dd0356c8b/src/leaflet.hotline.js#L24) has an issue when used as a module (like dynamic import are), also for this reason we might consider this integration quite experimental.

For now this is the logic behind it:

https://github.com/Raruto/leaflet-elevation/blob/c9a17e113cec8f8eaf86a66a6285c3583fd457e3/src/control.js#L417-L445

>  In your examples is hotline set to "speed" and "slope" also, but I don't see a coloured track like with "elevation". The track is always red.

I think the reason is quite simple, the `speed` and `slope` values in consideration are very small and there are not enough gradations to color those intervals:

https://github.com/Raruto/leaflet-elevation/blob/c9a17e113cec8f8eaf86a66a6285c3583fd457e3/src/control.js#L425-L431

Here you can see it quite easily (if you remove the `knots` part it should work as expected again):

https://github.com/Raruto/leaflet-elevation/blob/c9a17e113cec8f8eaf86a66a6285c3583fd457e3/examples/leaflet-elevation_speed-chart.html#L45-L47

At the moment I can't tell you how to solve, but as usual (when possible) I would prefer to avoid using hundreds of options that are too specific.


_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
> Ok. So I will realize in my plugin:
> > // hotline: false || "elevation"

Yep, I forgot to get back to you on that point, as you see it should accept `true`, `false` and any other `string` value.

https://github.com/Raruto/leaflet-elevation/blob/13fc8023be4a537616f371f112478859b739ee25/src/control.js#L419

In the case of a string, it must be the name of an attribute whose min / max values have been calculated (eg. `slope_max`, `slope_min`, `speed_max`, `speed_min`, ...), you should find them fairly easily within the `track_info` variable.

https://github.com/Raruto/leaflet-elevation/blob/13fc8023be4a537616f371f112478859b739ee25/src/control.js#L426-L427
