### ISSUE TITLE
Hotline tracks are all displayed on the same map if there are multiple maps on one page

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#201]
Hi Raruto,
unfortunately there is still a bug: if setting is `hotline: "elevation"`, all tracks are displayed on only one map, if there are multiple maps on one page. An example is [your example](https://leafext.info//leaflet-elevation/examples/leaflet-elevation_multiple-maps-hotline.html), which I modified.
Here is one of my examples:
![grafik](https://user-images.githubusercontent.com/73023225/168153944-2087ed3a-0cc3-4932-910b-9bcce667291f.png)

I think, this line, e.g. the function insertBefore is the problem. But I don't know, how to solve it.
https://github.com/Raruto/leaflet-elevation/blob/37372a5dcf0a68b9d520b1195a488fbd1f140869/src/control.js#L446

And you can see a second problem. The marker trkStart and trkStop should be on every map, but they are only present on one. With this I have other nice effects also, I will open another issue.

Thank you very much.

**Comment by Raruto** [comment]
Hi hupe,
take a look at the following thread: https://github.com/iosphere/Leaflet.hotline/issues/20#issuecomment-694174218

---

> And you can see a second problem. The marker trkStart and trkStop should be on every map, but they are only present on one. With this I have other nice effects also, I will open another issue.

Probably this happens because it always refers to the same objects:

https://github.com/Raruto/leaflet-elevation/blob/37372a5dcf0a68b9d520b1195a488fbd1f140869/src/control.js#L184-L185

https://github.com/Raruto/leaflet-elevation/blob/37372a5dcf0a68b9d520b1195a488fbd1f140869/src/options.js#L52-L53

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
Ok. With [this information](https://github.com/iosphere/Leaflet.hotline/issues/20#issuecomment-694174218) the hotline problem is easy to fix. See [here](https://leafext.info//leaflet-elevation/examples/leaflet-elevation_multiple-maps-hotline.html).  I will make a pull request.

**Comment by hupe13** [comment]
Thank you very much, now it works!
