### ISSUE TITLE
Is it possible to use custom waypoint icons for the elevation chart?

### ISSUE THREAD

**Issue by JonasDoe** [Raruto/leaflet-elevation#230]
### Subject of the issue
From the examples and the documentation I understand that I can create custom waypoint icons with the `wptIcons` property. But that only seems to affect the displayed map, not the elevation chart, which only features dots with texts. I'm not sure whether I'm missing something, though.

### Expected behaviour
In case I'm not missing some option, a flag, e.g. `type icons='MAP'|'CHART'|'BOTH'` would be nice, if it doesn't conflict with any other chart specific settings.

**Comment by Raruto** [comment]
Hi @JonasDoe

No, this is not a feature available out of the box, also because the `wptIcons` are nothing more than instances of leaflet icons:

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/src/options.js#L55-L62

Instead, svg markers are created manually in the elevation chart within this library with the aid of d3.js:

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/src/components/d3.js#L430-L487

Anyway, with the right javascript knowledge it shouldn't be too much difficult to a the current code to write a some dedicated functions for this purpose (eg. [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch) some built-in from `L.Control.Elevation.*`).

As a starting point, If you don't know where to start looking, you can also check out [leaflet-elevation_dynamic-runner.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_dynamic-runner.html) source code:

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/examples/leaflet-elevation_dynamic-runner.html#L47-L85

Anyway, keep in mind that:

- there are so many viable solutions, it's up to you to decide the one that best suits you, also try searching among the old issues to get an idea of how to proceed (eg: https://github.com/Raruto/leaflet-elevation/issues/100)
- feel free to create a dedicated pull request if you think this feature could be useful to someone else
- feel free to send a new example file if you think it is not necessary to change the current behavior of the plugin
- changes or additions to the current documentation are always welcome

👋 Raruto

**Comment by JonasDoe** [comment]
Alright, thank you for the directions!
