### ISSUE TITLE
Custom Start and End marker icons using the `"eledata_loaded"` event

### ISSUE THREAD

**Issue by haldo98** [Raruto/leaflet-elevation#239]
Thank you for your great work.

I'm a newbie in js so please forgive me if I'm writing something dumb

I have some issue with the gpxOptions inherited from leaflet-gpx

I added the options #18  of the marker from leaflet-gpx but the markers are not shown.

```
gpxOptions: {
marker_options: {
    startIconUrl: 'pin-icon-start.png',
    endIconUrl: 'pin-icon-end.png',
    shadowUrl: 'pin-shadow.png'
    },
},

```

Here is my working example:
https://www.tadini.it/temp/map.html

And.....    does the event from leaflet-gpx is supported?  (addpoint - loaded - error )

Thank You.

**Comment by Raruto** [comment]
In the latest versions of this library the `lealfet-gpx` dependency has been removed.

BTW, if you don't want to go crazy understanding too much third party code you can also do it directly adding two simple [L.Markers](https://leafletjs.com/reference.html#marker) (at the start and end of your path).

👋 Raruto

**Comment by haldo98** [comment]
Thank you.... is there a way to directly point to the start and the end of the track with the plugin or should I have two waypoints ?
(start-end)

thank u

**Comment by Raruto** [comment]
I think there are several ways to achieve this, just FYI, here you can change the properties related to the current start and end icons (if I remember correctly, even if they are [L.CircleMarkers](https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/src/control.js#L184-L185) with a little imagination you could also use icons, in case please search for this on the web and let me know..)

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/src/options.js#L52-L53

Otherwise here it is something old-fashioned:

```js
controlElevation.on('eledata_loaded', (e) => {
  console.log(e, controlElevation._data); // <-- here you can do something much more clever.. 😃
);

controlElevation.load(url);
```

👋 Raruto
