### ISSUE TITLE
How to  move cursor along the chart by code

### ISSUE THREAD

**Issue by abmcr** [Raruto/leaflet-elevation#27]
Hello. Thank you for your code.

In this [example](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_follow-marker.html) is it possible to move the cursor along the profile with code ?
What i want is create an animation.....

_Thank you_

**Comment by Raruto** [comment]
Nothing out of the box, but you can always write your own function according to the following:
https://github.com/Raruto/leaflet-elevation/blob/447201b70a50bacf432da2e21ab74c9083d34bbb/leaflet-elevation.js#L1330

In particular, these are the lines you need to pay more attention to:
```js
...

 // xCoord = current cursor position relative to elevation chart diagram

 var item = this._data[this._findItemForX(xCoord)];

 this._hidePositionMarker();
 this._showDiagramIndicator(item, xCoord);
 this._showPositionMarker(item);
 this._setMapView(item);

...
```

**Comment by rahan34** [comment]
Hi Raruto,

I post this issue here as it could help others too.

I'm trying to display several Points of  Interest using the DiagramIndicators on the elevation chart **on data load** (NOT on mouse move event). Something [like this](http://193.70.42.160/test/initialize%20chart.png) : 

I have carefully tried to understand all the events that could fire this event, without success.
I have created my function called **_showUserDiagramIndicator(item, xCoord);** and I could test it on **_mousemoveHandler** function (as you explained above). It displays what I want when I mouseover the chart.
But I cannot figure out how to call it on data load.
I have also tried to call **_showUserDiagramIndicator(item, xCoord);** in addData: function(d, layer) 
but the functions are not called with the same arguments so it does not work.

Any help is appreciated!
Thanks,
Paul
