### ISSUE TITLE
hotline and linearGradient

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#288]
Hi Raruto,

someone ask in my [forum](https://wordpress.org/support/topic/what-about-gradient-option/). Please see your [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_linear-gradient.html
). Shouldn't the colors of the track and the elevation profile be the same? Why aren't they?

Thank you very much.

**Comment by Raruto** [comment]
Hi hupe, if I recall correctly I don't think anyone else has ever dived into that code but me: https://github.com/Raruto/leaflet-elevation/pull/257#discussion_r1200109451

The color mismatch could be due to a different approximation used by leaflet to print its paths on the map. For overall performance the map should print fewer points depending on the current zoom level (unlike leaflet-elevation chart which always displays all of them).

As usual, anyone who wants to investigate is welcome.

👋 Raruto

**Comment by hupe13** [comment]
Thank you very much for your explanation.
