### ISSUE TITLE
Customization of map buttons and elevation plot

### ISSUE THREAD

**Issue by fgebhart** [Raruto/leaflet-elevation#37]
Great plugin - really like it and plan to integrate it into my current project.

I have some questions regarding the configuration of your plugin. I was already looking into `leaflet-elevation.js` but couldn't find what I am looking for - maybe because I barely have any js experience:

1. Is there a way to disable the buttons: "Print map", "Search...", "Show me where I am" and the "Google Street View manikin"? If so, how?
2. Is is possible to set specfic colors (e.g. hex code) for both the line in the map and the elevation plot (and background)? I am currently using Geojson as data input.

Would it be okay to open up more issues if I have more questions?

**Comment by Raruto** [comment]
Hi Fabian,

> 1. Is there a way to disable the buttons: "Print map", "Search...", "Show me where I am" and the "Google Street View manikin"? If so, how?

You're probably referring to this other plugin [leaflet-ui](https://github.com/Raruto/leaflet-ui) (it's not mandatory, but try to check it out anyway)

> 2. Is is possible to set specfic colors (e.g. hex code) for both the line in the map and the elevation plot (and background)? I am currently using Geojson as data input.

This [example](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_custom-theme.html) can help you in defining custom colors, otherwise, you can always try to use some default presets (see: `theme: "lightblue-theme"` option in readme file and the following file [leaflet-elevation.css](https://github.com/Raruto/leaflet-elevation/blob/master/leaflet-elevation.css) for some other default "*-theme" names)

> Would it be okay to open up more issues if I have more questions?

Maybe documentation is currently a bit sparse, if you have some time, try suggesting missing info in the [wiki](https://github.com/Raruto/leaflet-elevation/wiki) <-- you can also search through [closed issues](https://github.com/Raruto/leaflet-elevation/issues?q=is%3Aissue+is%3Aclosed) for frequently asked questions.

Anyway yes, if you have other questions a new issue is always better (so everyone can easily find it).

**Comment by fgebhart** [comment]
Great, thanks a lot.

Regarding the wiki. I don't thing that I can access the wiki?! I am redirected to the repos home. Maybe you have to activate it?

**Comment by Raruto** [comment]
> Regarding the wiki. I don't thing that I can access the wiki?! I am redirected to the repos home. Maybe you have to activate it?

oops, now it should work ...

**Comment by fgebhart** [comment]
thanks. I guess something like a collection of FAQs could be a good starting point.
