### ISSUE TITLE
Link to gpx outside of map

### ISSUE THREAD

**Issue by jbreslow** [Raruto/leaflet-elevation#39]
Is it possible to have a link to a gpx track that is outside of the map? I would like to list all of the GPX files in a left-side column, with the map loaded in the remaining right column ([similar to this layout](https://blackrockdigital.github.io/startbootstrap-resume/)). 

How can I accomplish this?

**Comment by Raruto** [comment]
Hi Josh,

as long as you know the urls of the gpx files, you can always use them in your own anchor links.

Otherwise, you can use the following options:

```js
    // Chart container outside/inside map container
    detached: true,

    // if (detached), the elevation chart container
    elevationDiv: "#elevation-div",
```

and put the `#elevation-div` where you like most on your page, eg:

```html
<div id="map" class="leaflet-map"></div>
<div id="elevation-div" class="elevation-div"></div>
```

If you also want to wait for the gpx file to be fully loaded, before displaying your link, you can also use take a look at the following hook

```js
map.on('eledata_loaded', function(e) {
  if (!controlLayer._map) controlLayer.addTo(map);
  controlLayer.addOverlay(e.layer, e.name);
});
```

See this [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation.html) for more info.

**Comment by jbreslow** [comment]
Hello,

I was just looking at this when I saw you closed it... Do you have an example of how to load the GPX file via the URL?

Thank you!
