### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by fabmor** [Raruto/leaflet-elevation#61]
hi, I can't upload a geojson or gpx file offline, can you help me please?

**Comment by Raruto** [comment]
Hello faber, 

for security reasons (in javascript) you are not allowed to "easily" read the content of local files without an explicit user intervention.

If you need just to do some quick tests, you can also do such a thing: [leaflet-elevation_string-data.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_string-data.html)

**index.html**

```html
<script href="./track.js"></script>
<script>
  var map = new L.Map('map', opts.map);
  var controlElevation = L.control.elevation(opts.elevationControl.options);
  controlElevation.load(data); // <-- defined within "track.js"
  controlElevation.addTo(map);
</script>
```

**track.js**
```js
const data = `
<gpx>
  <trk>
    <trkseg>
        <trkpt>
        ...
    <trkseg>
  </trk>
</gpx>
`.trim(); // <-- just for safety.
```

More info: [Javascript Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

---

otherwise, just use a "plain" json object:

```js
const data = {
  "type": "FeatureCollection",
    "features": [{
      "type": "Feature",
        "properties": {
          ...
        }
    }]
};
```

_Regards,
Raruto_

**Comment by fabmor** [comment]
Hello Raruto, thanks for the answer, your plugin is spectacular, I hope to succeed thanks to your advice to insert it in my maps. Thanks again
