### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by guillaumedc** [Raruto/leaflet-elevation#86]
Is there an exhaustive documentation, in which every option attributes are listed with possible values?

For instance:
  * what are the existing hooks? (found ```on('eledata_loaded', () => {})``` in examples)
  * what are the available themes?

**Comment by Raruto** [comment]
Hi Guillame,

> Is there an exhaustive documentation, in which every option attributes are listed with possible values?

Currently not, but the wiki is open for everyone to edit 😄.

About the possible options you can take a look at the [src/options.js](https://github.com/Raruto/leaflet-elevation/blob/master/src/options.js) file (although some may be missing anyway).

If it can help:

- `gpxOptions`: are the same options available for the `L.gpx` constructor (see the [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx) library for more info about it)
- `marker`: "elevation-line" || "elevation-line" || false
- `markerIcon`: [`L.divIcon`](https://leafletjs.com/reference#divicon) object
- `polyline` and `polylineSegments`: [`Polyline options`](https://leafletjs.com/reference#polyline-option)
https://github.com/Raruto/leaflet-elevation/blob/master/src/options.js (fore the `L.polyline` object)
- `downloadLink`: "link" || false || "modal" (listen for the `eletrack_download` for more info about it)
- `dragging`: true || false (default: automatically disabled on mobile)
- `lazyLoadJS`: true || false (default: automatically include `d3js` and `leaflet-gpx` scripts when not detected in global scope)
- `timeFormat`: "time" || "date" || false || your own custom formatting function (used when `time: true`, see [here](https://github.com/Raruto/leaflet-elevation/blob/936486b897a7f5e5827c0a06266ece3933b14711/src/time.js#L10) for more info)
- `placeholder`: (probably deprecated) attempted to load elevation data only when the detaced chart container entered the visible portion of the screen (see the [loadLazy](https://github.com/Raruto/leaflet-elevation/blob/6168c8e669cbb8aea83becc08c15f7ce9dddf9de/src/control.js#L206) function for more info)
- etc. etc.

> what are the existing hooks? (found on('eledata_loaded', () => {}) in examples)

There aren't too many, but you are interested can start by searching for the following functions within the source code:

- [`_fireEvt`](https://github.com/Raruto/leaflet-elevation/search?q=_fireEvt)
- [`fire`](https://github.com/Raruto/leaflet-elevation/search?q=fire)

If it can help, here are some fired by the `L.Control.Elevation` class:

- `eledata_added`
- `eledata_clear`
- `elepoint_added`
- `eletrack_added`
- `eledata_updated`
- `elechart_enter`
- `elechart_axis`
- `elechart_legend`
- `elechart_init`
- `elechart_dragged`
- `elechart_change`
- `elechart_hover`
- `elechart_leave`
- `elechart_area`
- `elechart_updated`
- `elechart_summary`
- `eletrack_download`
- `elepath_toggle`
- `waypoint_added`

**NB** I've never documented them because I think maybe someday I would have to change them to use a prefix to avoid "naming collisions" with other plugins (as you can see [here](https://github.com/Raruto/leaflet-elevation/blob/6168c8e669cbb8aea83becc08c15f7ce9dddf9de/src/control.js#L436) some of these are also fired by the **L.Map** class, maybe necessary for some of them, now is mainly for backward compatibility with the early former releases)

> what are the available themes?

At the time of writing (v 1.5.1) the classes defined within the [leaflet-elevation.css](https://github.com/Raruto/leaflet-elevation/wiki/FAQ#1-how-can-i-change-the-color-of-the-elevation-plot) file are the following:

- `lime-theme`
- `steelblue-theme`
- `purple-theme`
- `yellow-theme`
- `red-theme`
- `magenta-theme`
- `lightblue-theme`

Otherwirse, since the chart is still a valid `<svg>` element, you can always add your own [custom](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_custom-theme.html) css theming.

> how can we disable layer selection buttons, street view and other things?

You're referring to the [leflet-ui](https://github.com/Raruto/leaflet-elevation/wiki/FAQ#2-how-to-enabledisable-the-leaflet-user-interface-customizations) library (it's not mandatory, but you can just use it to speed up the work while setting up "another" new leaflet map).

In particular, pass the following options to the **L.map** constructor to disable the aforementioned controls:

```js
layersControl: false,
pegmanControl: false,
```

Otherwise just:

```js
disableDefaultUI: true,
```

_Thanks to anyone else who will lend a hand,
Raruto_

**Comment by guillaumedc** [comment]
Thank you very much for this documentation.
It has solve most of my concerns.
I'm really glad to found your lib, it does the job well!
