### ISSUE TITLE
Speed example and Units

### ISSUE THREAD

**Issue by mhaque02** [Raruto/leaflet-elevation#93]
Is there any example of the speed/acceleration graph? I added `speed: true` to the options but it just shows 0.

I am using a GeoJSON file with [latitude, longitude, altitude]

I did not see any examples or documentation regarding how to implement speed in the data or what it is using to calculate this. Additionally, is there any way to change units per data point? For example I would like the altitude to remain as feet but speed should be in terms of "knots" (for aviation)

**Comment by Raruto** [comment]
Hi Syam,

if I'm not mistaken, [geojson](https://geojson.org/) standard doesn't define a common format where to save `time` information (eg. inside the `properties` value).

If not provided, `time` information is not calculated programmatically by this library (as speed depends on time you always get 0).

---

For gpx files, time data is parsed within this event:  https://github.com/Raruto/leaflet-elevation/blob/42b557c928445064b6e48464913bbc3fe803155e/src/time.js#L18

(search for `meta` propery inside [mpetazzoni/leaflet-gpx/gpx.js](https://github.com/mpetazzoni/leaflet-gpx/blob/98772565059f832326bb4d7594b5c0bdfd0aa94d/gpx.js#L450) for more info)

Take a look at these other files to fully understand:
- [Raruto/leaflet-elevation/src/time.js](https://github.com/Raruto/leaflet-elevation/blob/master/src/time.js)
- [Raruto/leaflet-elevation/src/speed.js](https://github.com/Raruto/leaflet-elevation/blob/master/src/speed.js)
- [Raruto/leaflet-elevation/src/control.js#L346](https://github.com/Raruto/leaflet-elevation/blob/42b557c928445064b6e48464913bbc3fe803155e/src/control.js#L346)
- [Raruto/leaflet-elevation/src/control.js#L357](https://github.com/Raruto/leaflet-elevation/blob/42b557c928445064b6e48464913bbc3fe803155e/src/control.js#L357)

---

[Here](https://github.com/Raruto/leaflet-elevation/blob/master/libs/extended-ui.js) here you can find an example of how to write your own library in order to add a custom chart profile (eg. for "knots"). As usual, pull request are well accepted.

---

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
From version **1.5.5** you can use the following options:

```js
speed: true,
speedLabel: 'knts',
speedFactor: 0.539956803455724, // 1 km/h =  0.539956803455724 knots
```

Take a look at [speed-chart.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_speed-chart.html) and [time.geojson](https://github.com/Raruto/leaflet-elevation/blob/9f42f1768b3c7e970c556e560a0cd04f02b9e031/examples/time.geojson) for a complete example.

---


If needed, you can also use the following parameters:

```js
acceleration: true,
accelerationLabel: /* label */,
accelerationFactor: /* constant */,
```
See: [src/speed.js](https://github.com/Raruto/leaflet-elevation/blob/9f42f1768b3c7e970c556e560a0cd04f02b9e031/src/speed.js#L111) and [src/acceleration.js](https://github.com/Raruto/leaflet-elevation/blob/9f42f1768b3c7e970c556e560a0cd04f02b9e031/src/acceleration.js#L112) for more info about them.

---

_Happy testing,
Raruto_
