### ISSUE TITLE
Elapsed time on x-axis

### ISSUE THREAD

**Issue by giloutho** [Raruto/leaflet-elevation#94]
I would like to use leaflet-elevation to display paraglider GPS tracks. For the pilot, the raw distance of the track has no value. You can spend a lot of time turning in thermals to gain altitude. In the end, the distance as the crow flies between takeoff and landing will have no relation to the total distance of the GPS track. 

Is there a simple way to substitute elapsed time instead of distance on the x-axis ?

**Comment by Raruto** [comment]
Hi giloutho,
in version **1.5.6** I've added a top time axis:

![time-axis](https://user-images.githubusercontent.com/9614886/109171679-4dd21700-7782-11eb-8628-28249ffc51ea.png)

for those who want to keep it hidden:

```js
time: "summary"
```

**NB** on mobile phones, due to the limited space available, the time axis is disabled by default.

_Have a nice day,
Raruto_

**Comment by giloutho** [comment]
Thank you very much for this answer and especially for this very quick and efficient update. 

I will now have to dive deeper into the source code. I must create additional hooks. As in [issue#43](https://github.com/Raruto/leaflet-elevation/issues/43#issuecomment-642085473), I have to add other values in the graph: vertical speed and ground height. These values are in the geoJson. If I manage to incorporate them, it will be perfect. 

Your plugin is really a marvel. Thanks a lot.
