### ISSUE TITLE
controlElevation.load() URL encoding

### ISSUE THREAD

**Issue by RaunoT** [Raruto/leaflet-elevation#95]
Hello,

I am facing an issue where using `controlElevation.load()` doesn't seem to accept UTF-8 URL's.

Example usage:

```
console.log(gpx)
controlElevation.load(gpx);
```

The `console.log` returns `../uploads/Paluküla-1.8km.gpx`
But it throws a 404 at `controlElevation.load()` looking for `../uploads/Paluku%CC%88la-1.8km.gpx`

As you can see, the URL is not encoded correctly.
Any idea for the reasoning?

**Comment by Raruto** [comment]
Hi Rauno,

I tested a file with the same name and it seems to work fine to me:

```log
XHR GET http://localhost/leaflet-elevation/test/Paluku%CC%88la-1.8km.gpx [HTTP/1.1 200 OK 2ms]
```

Of course, the file might not really exist on your server... 

Otherwise, check carefully your **page** and **headers** encodings (try to search on [stackoverflow.com](http://stackoverflow.com) for more helpful stuff).

_Have a nice day,
Raruto_

**Comment by RaunoT** [comment]
You are correct, the problem was in my headers encoding.
Sorry for the trobule and thanks again!
